require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConflictsController do

  # This should return the minimal set of attributes required to create a valid
  # Conflict. As you add validations to Conflict, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConflictsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all conflicts as @conflicts" do
      conflict = Conflict.create! valid_attributes
      get :index, {}, valid_session
      assigns(:conflicts).should eq([conflict])
    end
  end

  describe "GET show" do
    it "assigns the requested conflict as @conflict" do
      conflict = Conflict.create! valid_attributes
      get :show, {:id => conflict.to_param}, valid_session
      assigns(:conflict).should eq(conflict)
    end
  end

  describe "GET new" do
    it "assigns a new conflict as @conflict" do
      get :new, {}, valid_session
      assigns(:conflict).should be_a_new(Conflict)
    end
  end

  describe "GET edit" do
    it "assigns the requested conflict as @conflict" do
      conflict = Conflict.create! valid_attributes
      get :edit, {:id => conflict.to_param}, valid_session
      assigns(:conflict).should eq(conflict)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Conflict" do
        expect {
          post :create, {:conflict => valid_attributes}, valid_session
        }.to change(Conflict, :count).by(1)
      end

      it "assigns a newly created conflict as @conflict" do
        post :create, {:conflict => valid_attributes}, valid_session
        assigns(:conflict).should be_a(Conflict)
        assigns(:conflict).should be_persisted
      end

      it "redirects to the created conflict" do
        post :create, {:conflict => valid_attributes}, valid_session
        response.should redirect_to(Conflict.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved conflict as @conflict" do
        # Trigger the behavior that occurs when invalid params are submitted
        Conflict.any_instance.stub(:save).and_return(false)
        post :create, {:conflict => {}}, valid_session
        assigns(:conflict).should be_a_new(Conflict)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Conflict.any_instance.stub(:save).and_return(false)
        post :create, {:conflict => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested conflict" do
        conflict = Conflict.create! valid_attributes
        # Assuming there are no other conflicts in the database, this
        # specifies that the Conflict created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Conflict.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => conflict.to_param, :conflict => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested conflict as @conflict" do
        conflict = Conflict.create! valid_attributes
        put :update, {:id => conflict.to_param, :conflict => valid_attributes}, valid_session
        assigns(:conflict).should eq(conflict)
      end

      it "redirects to the conflict" do
        conflict = Conflict.create! valid_attributes
        put :update, {:id => conflict.to_param, :conflict => valid_attributes}, valid_session
        response.should redirect_to(conflict)
      end
    end

    describe "with invalid params" do
      it "assigns the conflict as @conflict" do
        conflict = Conflict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Conflict.any_instance.stub(:save).and_return(false)
        put :update, {:id => conflict.to_param, :conflict => {}}, valid_session
        assigns(:conflict).should eq(conflict)
      end

      it "re-renders the 'edit' template" do
        conflict = Conflict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Conflict.any_instance.stub(:save).and_return(false)
        put :update, {:id => conflict.to_param, :conflict => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested conflict" do
      conflict = Conflict.create! valid_attributes
      expect {
        delete :destroy, {:id => conflict.to_param}, valid_session
      }.to change(Conflict, :count).by(-1)
    end

    it "redirects to the conflicts list" do
      conflict = Conflict.create! valid_attributes
      delete :destroy, {:id => conflict.to_param}, valid_session
      response.should redirect_to(conflicts_url)
    end
  end

end
