require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FirearmsController do

  # This should return the minimal set of attributes required to create a valid
  # Firearm. As you add validations to Firearm, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FirearmsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all firearms as @firearms" do
      firearm = Firearm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:firearms).should eq([firearm])
    end
  end

  describe "GET show" do
    it "assigns the requested firearm as @firearm" do
      firearm = Firearm.create! valid_attributes
      get :show, {:id => firearm.to_param}, valid_session
      assigns(:firearm).should eq(firearm)
    end
  end

  describe "GET new" do
    it "assigns a new firearm as @firearm" do
      get :new, {}, valid_session
      assigns(:firearm).should be_a_new(Firearm)
    end
  end

  describe "GET edit" do
    it "assigns the requested firearm as @firearm" do
      firearm = Firearm.create! valid_attributes
      get :edit, {:id => firearm.to_param}, valid_session
      assigns(:firearm).should eq(firearm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Firearm" do
        expect {
          post :create, {:firearm => valid_attributes}, valid_session
        }.to change(Firearm, :count).by(1)
      end

      it "assigns a newly created firearm as @firearm" do
        post :create, {:firearm => valid_attributes}, valid_session
        assigns(:firearm).should be_a(Firearm)
        assigns(:firearm).should be_persisted
      end

      it "redirects to the created firearm" do
        post :create, {:firearm => valid_attributes}, valid_session
        response.should redirect_to(Firearm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved firearm as @firearm" do
        # Trigger the behavior that occurs when invalid params are submitted
        Firearm.any_instance.stub(:save).and_return(false)
        post :create, {:firearm => {}}, valid_session
        assigns(:firearm).should be_a_new(Firearm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Firearm.any_instance.stub(:save).and_return(false)
        post :create, {:firearm => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested firearm" do
        firearm = Firearm.create! valid_attributes
        # Assuming there are no other firearms in the database, this
        # specifies that the Firearm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Firearm.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => firearm.to_param, :firearm => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested firearm as @firearm" do
        firearm = Firearm.create! valid_attributes
        put :update, {:id => firearm.to_param, :firearm => valid_attributes}, valid_session
        assigns(:firearm).should eq(firearm)
      end

      it "redirects to the firearm" do
        firearm = Firearm.create! valid_attributes
        put :update, {:id => firearm.to_param, :firearm => valid_attributes}, valid_session
        response.should redirect_to(firearm)
      end
    end

    describe "with invalid params" do
      it "assigns the firearm as @firearm" do
        firearm = Firearm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Firearm.any_instance.stub(:save).and_return(false)
        put :update, {:id => firearm.to_param, :firearm => {}}, valid_session
        assigns(:firearm).should eq(firearm)
      end

      it "re-renders the 'edit' template" do
        firearm = Firearm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Firearm.any_instance.stub(:save).and_return(false)
        put :update, {:id => firearm.to_param, :firearm => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested firearm" do
      firearm = Firearm.create! valid_attributes
      expect {
        delete :destroy, {:id => firearm.to_param}, valid_session
      }.to change(Firearm, :count).by(-1)
    end

    it "redirects to the firearms list" do
      firearm = Firearm.create! valid_attributes
      delete :destroy, {:id => firearm.to_param}, valid_session
      response.should redirect_to(firearms_url)
    end
  end

end
