require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LocationreportsController do

  # This should return the minimal set of attributes required to create a valid
  # Locationreport. As you add validations to Locationreport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocationreportsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all locationreports as @locationreports" do
      locationreport = Locationreport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:locationreports).should eq([locationreport])
    end
  end

  describe "GET show" do
    it "assigns the requested locationreport as @locationreport" do
      locationreport = Locationreport.create! valid_attributes
      get :show, {:id => locationreport.to_param}, valid_session
      assigns(:locationreport).should eq(locationreport)
    end
  end

  describe "GET new" do
    it "assigns a new locationreport as @locationreport" do
      get :new, {}, valid_session
      assigns(:locationreport).should be_a_new(Locationreport)
    end
  end

  describe "GET edit" do
    it "assigns the requested locationreport as @locationreport" do
      locationreport = Locationreport.create! valid_attributes
      get :edit, {:id => locationreport.to_param}, valid_session
      assigns(:locationreport).should eq(locationreport)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Locationreport" do
        expect {
          post :create, {:locationreport => valid_attributes}, valid_session
        }.to change(Locationreport, :count).by(1)
      end

      it "assigns a newly created locationreport as @locationreport" do
        post :create, {:locationreport => valid_attributes}, valid_session
        assigns(:locationreport).should be_a(Locationreport)
        assigns(:locationreport).should be_persisted
      end

      it "redirects to the created locationreport" do
        post :create, {:locationreport => valid_attributes}, valid_session
        response.should redirect_to(Locationreport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved locationreport as @locationreport" do
        # Trigger the behavior that occurs when invalid params are submitted
        Locationreport.any_instance.stub(:save).and_return(false)
        post :create, {:locationreport => {}}, valid_session
        assigns(:locationreport).should be_a_new(Locationreport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Locationreport.any_instance.stub(:save).and_return(false)
        post :create, {:locationreport => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested locationreport" do
        locationreport = Locationreport.create! valid_attributes
        # Assuming there are no other locationreports in the database, this
        # specifies that the Locationreport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Locationreport.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => locationreport.to_param, :locationreport => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested locationreport as @locationreport" do
        locationreport = Locationreport.create! valid_attributes
        put :update, {:id => locationreport.to_param, :locationreport => valid_attributes}, valid_session
        assigns(:locationreport).should eq(locationreport)
      end

      it "redirects to the locationreport" do
        locationreport = Locationreport.create! valid_attributes
        put :update, {:id => locationreport.to_param, :locationreport => valid_attributes}, valid_session
        response.should redirect_to(locationreport)
      end
    end

    describe "with invalid params" do
      it "assigns the locationreport as @locationreport" do
        locationreport = Locationreport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Locationreport.any_instance.stub(:save).and_return(false)
        put :update, {:id => locationreport.to_param, :locationreport => {}}, valid_session
        assigns(:locationreport).should eq(locationreport)
      end

      it "re-renders the 'edit' template" do
        locationreport = Locationreport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Locationreport.any_instance.stub(:save).and_return(false)
        put :update, {:id => locationreport.to_param, :locationreport => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested locationreport" do
      locationreport = Locationreport.create! valid_attributes
      expect {
        delete :destroy, {:id => locationreport.to_param}, valid_session
      }.to change(Locationreport, :count).by(-1)
    end

    it "redirects to the locationreports list" do
      locationreport = Locationreport.create! valid_attributes
      delete :destroy, {:id => locationreport.to_param}, valid_session
      response.should redirect_to(locationreports_url)
    end
  end

end
